"""create stems

Revision ID: 089d97e511d0
Revises: 410617d0c244
Create Date: 2026-05-17 17:38:32.581240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089d97e511d0'
down_revision: Union[str, None] = '410617d0c244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('song_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'separating', 'separated', 'failed', name='stems_status'), nullable=False),
    sa.Column('vocals_path', sa.String(), nullable=True),
    sa.Column('drums_path', sa.String(), nullable=True),
    sa.Column('bass_path', sa.String(), nullable=True),
    sa.Column('other_path', sa.String(), nullable=True),
    sa.Column('vocal_rms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('stems')
    sa.Enum(name='stems_status').drop(op.get_bind(), checkfirst=False)
