"""create mix_plans

Revision ID: 103c84d416bc
Revises: db729e2f9c53
Create Date: 2026-05-19 18:37:24.336001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '103c84d416bc'
down_revision: Union[str, None] = 'db729e2f9c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mix_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.Column('from_song_id', sa.UUID(), nullable=False),
    sa.Column('to_song_id', sa.UUID(), nullable=False),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rendered_audio_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'rendering', 'ready', 'failed', name='mix_plan_status'), nullable=False),
    sa.Column('error_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_id', 'from_song_id', 'to_song_id', name='uq_mix_plan_pair')
    )
    op.create_index(op.f('ix_mix_plans_queue_id'), 'mix_plans', ['queue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_mix_plans_queue_id'), table_name='mix_plans')
    op.drop_table('mix_plans')
    # Autogenerated downgrades leak the enum type; drop it explicitly so
    # `downgrade base` -> `upgrade head` round-trips cleanly. Same pattern
    # as the transcription / stems / analyses / songs migrations.
    sa.Enum(name='mix_plan_status').drop(op.get_bind(), checkfirst=False)
