"""create transcriptions

Revision ID: 4065b47d2200
Revises: 089d97e511d0
Create Date: 2026-05-18 17:15:14.793683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4065b47d2200'
down_revision: Union[str, None] = '089d97e511d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('song_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('not_attempted', 'success', 'skipped_instrumental', 'error', name='transcription_status'), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vocal_rms_threshold', sa.Float(), nullable=True),
    sa.Column('vocal_rms_observed', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('transcriptions')
    # Autogenerated downgrades leak the enum type; drop it explicitly so
    # `downgrade base` -> `upgrade head` round-trips cleanly. Same pattern
    # as the stems / analyses / songs migrations.
    sa.Enum(name='transcription_status').drop(op.get_bind(), checkfirst=False)
