"""add pipeline_requested to song

Revision ID: 76d2da8e5066
Revises: a2657eccd290
Create Date: 2026-05-29 15:21:44.283388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d2da8e5066'
down_revision: Union[str, None] = 'a2657eccd290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('pipeline_requested', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'pipeline_requested')
    # ### end Alembic commands ###
