"""create lyrics table

Revision ID: a2657eccd290
Revises: dda3b1fbd945
Create Date: 2026-05-27 01:29:04.564495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2657eccd290'
down_revision: Union[str, None] = 'dda3b1fbd945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lyrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('song_id', sa.UUID(), nullable=False),
    sa.Column('genius_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('fetch_status', sa.Enum('not_attempted', 'success', 'not_found', 'error', name='lyricsfetchstatus'), nullable=False),
    sa.Column('aligned_words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alignment_status', sa.Enum('not_attempted', 'success', 'whisper_only', 'low_quality', 'error', name='lyricsalignmentstatus'), nullable=False),
    sa.Column('alignment_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lyrics')
    # ### end Alembic commands ###
