"""create analyses

Revision ID: b405ad4bc5e4
Revises: ae8d08dfa1e3
Create Date: 2026-05-17 00:25:09.917040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b405ad4bc5e4'
down_revision: Union[str, None] = 'ae8d08dfa1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('song_id', sa.UUID(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('camelot_key', sa.String(), nullable=False),
    sa.Column('time_signature', sa.Integer(), nullable=False),
    sa.Column('beat_grid', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('downbeats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('energy_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vocal_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    # ### end Alembic commands ###
