"""create queue renders

Revision ID: dda3b1fbd945
Revises: 103c84d416bc
Create Date: 2026-05-26 23:57:06.918597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda3b1fbd945'
down_revision: Union[str, None] = '103c84d416bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_renders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.Column('rendered_audio_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'rendering', 'ready', 'failed', name='queue_render_status'), nullable=False),
    sa.Column('error_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_renders')
    sa.Enum('pending', 'rendering', 'ready', 'failed', name='queue_render_status').drop(op.get_bind())
    # ### end Alembic commands ###
